# Generated by Django 3.2 on 2022-01-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20220122_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social_Account',
            new_name='SocialAccount',
        ),
    ]
