# Generated by Django 3.2 on 2022-01-23 15:59

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_rename_social_account_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='user', unique=True),
        ),
    ]
