# Generated by Django 3.2 on 2022-01-22 02:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_social_social_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social_account',
            options={'verbose_name_plural': 'Social Accounts'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='user', unique=True),
        ),
    ]
