# Generated by Django 3.2 on 2022-01-22 02:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220122_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='<property object at 0x7f53e4a939a0>', unique=True),
        ),
    ]
