# Generated by Django 3.2 on 2022-01-23 15:59

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0004_auto_20220123_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('zipcode', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('area', models.IntegerField()),
                ('video', models.FileField(null=True, upload_to='videos/property_videos/')),
                ('property_type', models.CharField(choices=[('agricultural', 'Agricultural'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('residential', 'Residential'), ('special use', 'Special Use')], default='residential', max_length=30, verbose_name='PropertyType')),
                ('status', models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], default='sale', max_length=10, verbose_name='Status')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='address', unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_agent', to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/property-images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_property', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_property', to='properties.property')),
            ],
        ),
    ]
