# Generated by Django 3.2 on 2022-01-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'verbose_name_plural': 'Property Images'},
        ),
        migrations.AlterField(
            model_name='property',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/property_videos/'),
        ),
    ]
