# Generated by Django 3.2 on 2022-01-24 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_auto_20220123_1559'),
        ('properties', '0002_auto_20220123_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
