# Generated by Django 3.2 on 2022-01-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20220124_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='name',
            new_name='amenity',
        ),
    ]
