# Generated by Django 3.2 on 2022-01-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_rename_name_amenity_amenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='amenity',
            field=models.CharField(max_length=500),
        ),
    ]
