# Generated by Django 3.2 on 2022-01-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_amenity_amenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='properties.property'),
        ),
    ]
