# Generated by Django 3.2 on 2022-01-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_picture',
            field=models.ImageField(default='image', upload_to='image/property_images'),
            preserve_default=False,
        ),
    ]
